name: flutter_memory_game
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^3.1.3
  provider: ^6.1.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  path_provider: ^2.1.2
  firebase_storage: ^12.3.4
  camera: ^0.11.0+2
  video_player: ^2.8.2
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - assets/images/level_one_images/.
    - assets/images/level_two_images/.
    - assets/images/level_three_images/.
    - assets/brain_animation.json
  #   - images/a_dot_ham.jpeg
