// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEckG_IYp6p5Y9EYVKlReHWWDAAEo9MAA',
    appId: '1:784579046439:web:c739b2955c938b15f37202',
    messagingSenderId: '784579046439',
    projectId: 'cardmatch-e7f12',
    authDomain: 'cardmatch-e7f12.firebaseapp.com',
    storageBucket: 'cardmatch-e7f12.appspot.com',
    measurementId: 'G-RVCQTHGPC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7lSmWhosLv8X9wVkSbHTvDTTTCKa2qY',
    appId: '1:784579046439:android:e393443c26c66532f37202',
    messagingSenderId: '784579046439',
    projectId: 'cardmatch-e7f12',
    storageBucket: 'cardmatch-e7f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDERUXFQRvN3XYoQ_-5O23z7yj3h9c7eaQ',
    appId: '1:784579046439:ios:4e07ede13cc5edc2f37202',
    messagingSenderId: '784579046439',
    projectId: 'cardmatch-e7f12',
    storageBucket: 'cardmatch-e7f12.appspot.com',
    iosBundleId: 'com.NAU.MemoryMatchGameAdmin',
  );

}